'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property Eid As Integer
    Public Property Ename As String
    Public Property JoinDate As Nullable(Of Date)
    Public Property Desingnation As String
    Public Property Salary As Nullable(Of Decimal)

End Class
